language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  api_key:
    secure: qnVUI1qTs3f2tkU3r1EUpg9nciFd023uWIRUTwiit/ePZfqGukMZ4Hj8WWt9ZFIU3qbhLtnBeEy0lj3KQc3wNi+8cFm+9ALEhS42EZvTY/QrXle+aAmZQiTlg2u4YYkxY18ANl0LTxYlXhe/KqdKi0FEmi27OdKdugj8bJDBl5e4XF3pgeANUVm1fcfn+s/Csotnl5s87cI0DfaEHZY+lJAHdVqqW7uM4+rSwM2n0II0CEWGZSKdidCN98JuLJ0eDN57VFZaqVkrmWfOx201wF7fazLO5FLfX95TaqEif2LgMenbj0Y/KA1Er0kfdNIAJGGUgJ61Op2tdbq+g6cdefcEiglGGTK0MxZRncne+bMjrTy2no3FXzfZOSCdgsDX8DSWQehQH5AucTEolNiraAcVfZ0V6OM1Q5SRmZvKuSe9t2YdkuMyim2xbAHsmvmcR15+7Eq9XQy+EgmCUZvXn/sBrVHv7W0vMj72p0vo3GKoi8Mm5jJK2U9JJrA2jlRFbPxQsB7Q04mgGSQo9j5NZ3+LF1e3DwL+HmAhVqP3HKVn1I2cT6OulAF816q2YFueB25NLnsIZ2HA8pVMBcSeYEkZsIvb4MppOvgupmcliZqcjw0IAcF/vmhnhFGIUAFsaV43YX8ERpNUnPWHty+dMAfjSKsp0jJTDfKLU3RTaDg=
  app: stormy-brushlands-60223
  on:
    repo: Jakousa/ratebeer
